### ISSUE TITLE
跑jdchain sdk-sample注册用户测试用例报错

### ISSUE THREAD

**Issue by karott** [blockchain-jd-com/jdchain#10]
前提：部署4个peer和一个gateway，均能正常访问
问题：跑sdk-sample注册用户测试用例报以下错误，说没注册(但是数据区块貌似也写进去了的)，请帮忙看下呢，谢谢
![image](https://user-images.githubusercontent.com/3212080/56346938-c74b6680-61f5-11e9-981d-970776b7a867.png)

另外  bftsmart默认共识算法需要启4个peer，这个怎么在本地方便的debug哦

**Comment by zhaoGuangwei** [comment]
谢谢您的反馈，如果调试bftsmart有点麻烦，您需要把bftsmart源码copy到jdchain工程。这样本地就可以debug。注册用户您要是通过另外的jdchain-starter工程的IntegrationTest.java中的registerUser_more()方法能跑通吗？如果仍然不行，可以将问题反馈到：jdchain-support@jd.com，我们跟您通过微信等方式直接快速沟通，谢谢

**Comment by karott** [comment]
> 谢谢您的反馈，如果调试bftsmart有点麻烦，您需要把bftsmart源码copy到jdchain工程。这样本地就可以debug。注册用户您要是通过另外的jdchain-starter工程的IntegrationTest.java中的registerUser_more()方法能跑通吗？如果仍然不行，可以将问题反馈到：[jdchain-support@jd.com](mailto:jdchain-support@jd.com)，我们跟您通过微信等方式直接快速沟通，谢谢

好的 谢谢！ 我后面发到邮箱一下
