### ISSUE TITLE
4个节点初始化失败

### ISSUE THREAD

**Issue by dengjinhmm** [blockchain-jd-com/jdchain#11]
一台电脑部署4个节点，同时运行ledger-init.sh,4个节点ledger-init.sh 内容一致 包括ledger.seed 和4个节点的公钥配置，其中只有一个节点成功，另外3个都报 Error!! -- Participant already exist!，

**Comment by zhaoGuangwei** [comment]
同一台电脑，seed是相同的，其它的配置信息是独立的。比如：不同的端口号、不同的公钥。记住：本质上是在同一台电脑上模拟四个不同的用户，所以你要采用四份不同的配置，是不是？如果仍有问题，可以联系：jdchain-support@jd.com，留下自己的联系方式，届时我们会提供一对一的专属服务。谢谢！

**Comment by zhaoGuangwei** [comment]
三个配置文件：bftsmart.config  ledger-init.conf  local.conf。其中：ledger-init.conf，在几个不同的节点中配置是一样的，其它的文件则需要根据生成的key来填写各自的内容。 愉快！

**Comment by dengjinhmm** [comment]
bftsmart.config 4个节点不一样吗  我看默认要把4个节点的公钥都要填写，这样4个节点的bftsmart.config 就都一样了呀


------------------ 原始邮件 ------------------
发件人: "Zhao Guangwei"<notifications@github.com>;
发送时间: 2019年4月22日(星期一) 中午1:54
收件人: "blockchain-jd-com/jdchain"<jdchain@noreply.github.com>;
抄送: "956454822"<956454822@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [blockchain-jd-com/jdchain] 4个节点初始化失败 (#11)




三个配置文件：bftsmart.config  ledger-init.conf  local.conf。其中：ledger-init.conf，在几个不同的节点中配置是一样的，其它的文件则需要根据生成的key来填写各自的内容。 愉快！

**Comment by zhaoGuangwei** [comment]
你说的对！你先用rocksdb来熟悉环境，把rocks.db中的内容清理了再启动。

**Comment by dengjinhmm** [comment]
4个节点需要连接不同账本数据库 我切换不同的db能运行成功
