### ISSUE TITLE
Build Error - Failure to find com.yahoo.ycsb:core:jar:0.1.4 in https://repo.maven.apache.org/maven2

### ISSUE THREAD

**Issue by junahan** [blockchain-jd-com/jdchain#13]
通过 Git 更新至最新版本，在干净的环境下执行：
maven clean package -Dmaven.test.skip=true。

没有通过 Build - 看起来仍然是依赖包com.yahoo.ycsb:core:jar:0.1.4 无法通过 maven2  repository 找到。这个包的地址在 - http://kompics.sics.se/maven/repository/ 上，需要在 POM 里面配置该 repository 才行。

具体的出错信息如下：
[INFO] ledger-rpc ......................................... SUCCESS [  0.215 s]
[INFO] contract-maven-plugin .............................. SUCCESS [  1.729 s]
[INFO] consensus-bftsmart ................................. FAILURE [  0.031 s]
[INFO] consensus-mq ....................................... SKIPPED
[INFO] storage-redis ...................................... SKIPPED
[INFO] storage-rocksdb .................................... SKIPPED
[INFO] storage-composite .................................. SKIPPED
[INFO] gateway ............................................ SKIPPED
[INFO] tools-initializer .................................. SKIPPED
[INFO] peer ............................................... SKIPPED
[INFO] sdk-samples ........................................ SKIPPED
[INFO] tools-keygen-booter ................................ SKIPPED
[INFO] tools-initializer-booter ........................... SKIPPED
[INFO] tools-capability ................................... SKIPPED
[INFO] test ............................................... SKIPPED
[INFO] test-consensus-client .............................. SKIPPED
[INFO] test-consensus-node ................................ SKIPPED
[INFO] test-ledger-core ................................... SKIPPED
[INFO] test-integration ................................... SKIPPED
[INFO] deployment ......................................... SKIPPED
[INFO] deployment-gateway ................................. SKIPPED
[INFO] deployment-peer .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.602 s
[INFO] Finished at: 2019-04-24T13:57:02+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project consensus-bftsmart: Could not resolve dependencies for project com.jd.blockchain:consensus-bftsmart:jar:0.9.0-SNAPSHOT: Failure to find com.yahoo.ycsb:core:jar:0.1.4 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :consensus-bftsmart
TiedangdeMacBook-Pro:source junahan$

**Comment by huanghaiquan** [comment]
You need to compile and install another dependent project  bftsmart, which is located at https://github.com/blockchain-jd-com/bftsmart. 
You can found a core.jar file in the lib directory under the bftsmart project root directory, and then, install it to your local maven repository with artifact id “com.yahoo.ycsb:core:jar:0.1.4”.
