### ISSUE TITLE
Duplicate class org.apache.commons.logging.Log found in modules commons-logging-1.2.jar (commons-logging:commons-logging:1.2) and spring-jcl-5.0.10.RELEASE.jar (org.springframework:spring-jcl:5.0.10.RELEASE)

### ISSUE THREAD

**Issue by zhupengxiang** [blockchain-jd-com/jdchain#14]
android studio gradle 引入implementation 'com.jd.blockchain:sdk-client:0.8.3.RELEASE'后运行报错
org.apache.commons.logging.Log冲突 请问怎么解决

java.lang.RuntimeException: Duplicate class org.apache.commons.logging.Log found in modules commons-logging-1.2.jar (commons-logging:commons-logging:1.2) and spring-jcl-5.0.10.RELEASE.jar (org.springframework:spring-jcl:5.0.10.RELEASE)
  Duplicate class org.apache.commons.logging.LogFactory found in modules commons-logging-1.2.jar (commons-logging:commons-logging:1.2) and spring-jcl-5.0.10.RELEASE.jar (org.springframework:spring-jcl:5.0.10.RELEASE)
  Duplicate class org.apache.commons.logging.LogFactory$1 found in modules commons-logging-1.2.jar (commons-logging:commons-logging:1.2) and spring-jcl-5.0.10.RELEASE.jar (org.springframework:spring-jcl:5.0.10.RELEASE)
  Duplicate class org.apache.commons.logging.LogFactory$2 found in modules commons-logging-1.2.jar (commons-logging:commons-logging:1.2) and spring-jcl-5.0.10.RELEASE.jar (org.springframework:spring-jcl:5.0.10.RELEASE)
  Duplicate class org.apache.commons.logging.impl.NoOpLog found in modules commons-logging-1.2.jar (commons-logging:commons-logging:1.2) and spring-jcl-5.0.10.RELEASE.jar (org.springframework:spring-jcl:5.0.10.RELEASE)
  Duplicate class org.apache.commons.logging.impl.SimpleLog found in modules commons-logging-1.2.jar (commons-logging:commons-logging:1.2) and spring-jcl-5.0.10.RELEASE.jar (org.springframework:spring-jcl:5.0.10.RELEASE)

**Comment by huanghaiquan** [comment]
Eclude the duplicated jars, if this is a maven project , like this: 

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

**Comment by zhupengxiang** [comment]
我是android studio创建的项目   使用的gradle   关键我现在不知道排除哪个jar

**Comment by zhupengxiang** [comment]
spring-jcl:5.0.10和commons-logging-1.2 随便Eclude 一个就可以吗

**Comment by huanghaiquan** [comment]
You need to make the choice base on your project, we can't give advice.
