### ISSUE TITLE
第二次执行合约交易方法报错：The accessing index is out of BytesSlice's bounds

### ISSUE THREAD

**Issue by dengjinhmm** [blockchain-jd-com/jdchain#15]
第一执行合约方法没问题，参数不变重新执行就报错；
节点错误信息：java.lang.IllegalStateException: LedgerEditor had been committed!
网关错误：2 // 1 // TIMEOUT // Replies received: 0
15:57:59.072 ERROR com.jd.blockchain.gateway.web.GatewayGlobalExceptionHandler 34 json - Unexpected exception occurred! --[RequestURL=[POST] http://xx.xx.xx:xxxx/rpc/tx][class java.lang.NullPointerException]null java.lang.NullPointerException: null
	at com.jd.blockchain.binaryproto.BinaryEncodingUtils.decode(BinaryEncodingUtils.java:40) ~[binary-proto-0.8.3.RELEASE.jar!/:0.8.3.RELEASE]
	at com.jd.blockchain.sdk.service.NodeSigningAppender.process(NodeSigningAppender.java:78) ~[sdk-base-0.8.3.RELEASE.jar!/:0.8.3.RELEASE]
	at com.jd.bl

**Comment by zhaoGuangwei** [comment]
你的合约内容是什么？

**Comment by dengjinhmm** [comment]
HashDigest ledgerHash = new HashDigest(Base58Utils.decode(ledger));
TransactionTemplate txTemp = bcsrv.newTransaction(ledgerHash);
// 合约地址
String contractAddressBase58 = "5SmDCexiSTZdPP2nod1vFWLRPLcDcCeEAuqB";
String event = "transfer-asset";
byte[] args = "5SmFJZJPZskHzyz386NWhcHbxHxzVEWc5tE4##5SmJXuTcBWxWL28kSBaH3z5AVSCwL5KsPxhm##50.55555".getBytes();
// 提交合约执行代码
txTemp.contractEvents().send(contractAddressBase58, event, args); // TX 准备就绪;
PreparedTransaction prepTx = txTemp.prepare();
// 生成私钥并使用私钥进行签名;
BlockchainKeyPair blockchainKeyPair = BlockchainKeyGenerator.getInstance().generate();
prepTx.sign(blockchainKeyPair);
// 提交交易;
TransactionResponse transactionResponse = prepTx.commit();
return transactionResponse.isSuccess();

**Comment by dengjinhmm** [comment]
使用网关的私钥也一样报错

**Comment by dengjinhmm** [comment]
System.out.println("in AssetContractImpl transfer()");
		byte[] args_ = eventContext.getArgs();
		if (args_ == null) {
			return;
		}

		String[] args = new String(args_).split(BaseConstant.DELIMETER_DOUBLE_ALARM);
		System.out.println("arg_" + new String(args_));
		// 资产转出的账户;
		String fromAddress = args[0];
		// 校验"转出账户"是否已签名;
		//checkSignerPermission(fromAddress);

		// 资产转入的账户;
		String toAddress = args[1];

		// 转账的资产数量;
		BigDecimal amount = new BigDecimal(args[2]);
		//long amount = Long.parseLong(args[2]);
		if (amount.compareTo(BigDecimal.ZERO) < 0) {
			throw new ContractException("The amount is negative!");
		}
		if (amount.compareTo(BigDecimal.ZERO) == 0) {
			return;
		}

		HashDigest hashDigest = eventContext.getCurrentLedgerHash();

		// 查询现有的余额;
		KVDataEntry[] kvEntries = eventContext.getLedger().getDataEntries(hashDigest, ASSET_ADDRESS, KEY_TOTAL,
				fromAddress, toAddress);
		KVDataObject currTotal = (KVDataObject) kvEntries[0];
		KVDataObject fromBalance = (KVDataObject) kvEntries[1];
		KVDataObject toBalance = (KVDataObject) kvEntries[2];
		System.out.println("currTotal: " + currTotal.stringValue());

		// 检查是否余额不足;
		if ((new BigDecimal(fromBalance.stringValue()).compareTo(amount) < 0)) {
			throw new ContractException("Insufficient balance!");
		}

		// 把数据的更改写入到账本;
		BigDecimal newFromBalance = new BigDecimal(fromBalance.stringValue()).subtract(amount).setScale(8);
		System.out.println("newFromBalance: " + newFromBalance);
		BigDecimal newToBalance;
		if (toBalance.isNil()) {
			newToBalance = amount;
		} else {
			newToBalance = new BigDecimal(toBalance.stringValue()).add(amount);
		}
		System.out.println("newToBalance: " + newToBalance);

		// 转移from资产到to账户
		long fromVersion = fromBalance.getVersion();
		long toVersion = toBalance.getVersion();
		System.out.println("fromVersion = " + fromVersion);
		System.out.println("toVersion = " + toVersion);
		eventContext.getLedger().dataAccount(ASSET_ADDRESS).set(fromAddress, newFromBalance.toString(), fromVersion)
				.getOperation();
		eventContext.getLedger().dataAccount(ASSET_ADDRESS).set(toAddress, newToBalance.toString(), toVersion)
				.getOperation();

**Comment by dengjinhmm** [comment]
HashDigest ledgerHash = new HashDigest(Base58Utils.decode(ledger));
TransactionTemplate txTemp = bcsrv.newTransaction(ledgerHash);
// 合约地址
String contractAddressBase58 = "5SmDCexiSTZdPP2nod1vFWLRPLcDcCeEAuqB";
//执行资产交易的合约方法
String event = "transfer-asset";
byte[] args = "5SmFJZJPZskHzyz386NWhcHbxHxzVEWc5tE4##5SmJXuTcBWxWL28kSBaH3z5AVSCwL5KsPxhm##50.55555".getBytes();
// 提交合约执行代码
txTemp.contractEvents().send(contractAddressBase58, event, args); // TX 准备就绪;
PreparedTransaction prepTx = txTemp.prepare();
// 生成私钥并使用私钥进行签名;
BlockchainKeyPair blockchainKeyPair = BlockchainKeyGenerator.getInstance().generate();
prepTx.sign(blockchainKeyPair);
// 提交交易;
TransactionResponse transactionResponse = prepTx.commit();
return transactionResponse.isSuccess();

**Comment by zhaoGuangwei** [comment]
你先把StringValue()方法改为：getValue().toString( )试试。

**Comment by zhaoGuangwei** [comment]
我在https://github.com/blockchain-jd-com/jdchain-starter中也添加了你这个样例，你可以参考看看。AssetContractImpl1.java。

**Comment by dengjinhmm** [comment]
一个合约没有自带事务吗 我执行失败后资产统计不对,几个账户加起来多了50 多 ，就是转账失败那次的帐
![image](https://user-images.githubusercontent.com/29300542/56876081-89610480-6a77-11e9-9937-47947cfe9dbc.png)

**Comment by dengjinhmm** [comment]
你的样例我也试了 同样的转账合约参数连续执行2次，第二次会失败，第三次当我修改参数比如金额时会执行成功，但是toAddress地址的最终金额会把第二次执行失败的金额算上去，而fromAddress则不会，看起来是第二次fromAddress写入数据报错导致第二次执行失败

**Comment by dengjinhmm** [comment]
还有就是不知道在2个账户写入数据时候有没有相关事务处理

**Comment by zhaoGuangwei** [comment]
兄弟or老妹，你这个问题，可能我无法用言语来解答了，特意给你录制了一个视频。仅供个人学习交流使用，请勿进行商业传播。https://3.cn/NpUetSZ。
注意事项：1）地址需要在链上有；2）视频最后将int类型数据特意改为abc这样的字符串，构建异常。
您看看视频，希望能有所帮助。愉快！

**Comment by dengjinhmm** [comment]
OK 我使用你的测试方法deploy_exe_contract_on_test_gateway()没问题，而我是用代码示例中的合约调用方法txTemp.contractEvents().send()。deploy_exe_contract_on_test_gateway()方法是先发布再执行合约，难道每次交易都要生成一个新的合约地址？

**Comment by springtty** [comment]
我也奇怪，事务需要自己控制吗？在框架层面有没有办法控制的？

**Comment by zhaoGuangwei** [comment]
dengjinhmm 和 springtty两位朋友，你们好！谢谢你们针对这个问题的反馈。事务不需要自己控制，我们在框架里已经进行了处理，如果有问题会进行回滚。我根据dengjinhmm朋友的测试方法，用sdk重新运行了多遍。确实存在dengjinhmm朋友说的情况。原因也已经排查到，是底层强校验的问题。我们会在下一个版本中完善此问题。如果方便的话，可以在这里或者jdchain-support@jd.com中留下您的个人信息，我们会在新版本中收录此问题，以示对您的感谢。目前的变通使用方法可以这样处理（contractArgs参数内容适当调整）：
比如：
第一次：
contractArgs=fromAddr##toAddr##100
第二次：
contractArgs=fromAddr##toAddr##99
第三次：
contractArgs=fromAddr##toAddr##98
这种应急办法我觉得都恶心，我们会尽快更正。给您造成的不便，敬请谅解。
产品的不断进步还需要你们的热心参与，希望你们能够一如既往的多给我们找问题，提意见，非常感谢！
