### ISSUE TITLE
有没有API可以根据账户查询他数据变更记录

### ISSUE THREAD

**Issue by dengjin001** [blockchain-jd-com/jdchain#16]
简单地说就是根据账户地址查询他的交易记录

**Comment by zhaoGuangwei** [comment]
这个库里有数据，技术上容易实现。我把您的想法跟产品反馈一下，这个建议很好，多谢！

**Comment by dengjinhmm** [comment]
还有几个问题：
1.执行合约抛出了异常，虽然数据没有提交成功，但是在浏览器中区块显示执行状态是成功，除了查看日志和查看账户数据是否变化，我无法在代码层确认合约执行的结果。
2.合约是否支持返回值？怎样获取返回值？ContractDeployExeUtil.instance.exeContract和prepare.commit()执行的结果似乎都是数据上区块的结果，没有合约执行的结果

**Comment by huanghaiquan** [comment]
关于第1个问题，希望您可以把更详细的信息发给我们 jdchain-support@jd.com，最好包括日志信息。
关于第2个问题，我们已经加入到新版本的特性中，预计这个月底可以发布。

**Comment by dengjin001** [comment]
我在合约中主动抛出错误，日志正常报错，虽然最终账户余额没有问题，但是prepare.commit() 返回的TransactionResponse.isSuccess是true,而且区块中的执行状态是成功。我没有什么好办法确认这次调用合约是失败的 -_-
![image](https://user-images.githubusercontent.com/29300542/58158353-dc139200-7cac-11e9-9f24-bbb0f82cbd88.png)
![image](https://user-images.githubusercontent.com/29300542/58158388-ed5c9e80-7cac-11e9-9259-aab4516d39a0.png)
