### ISSUE TITLE
一个节点的redis数据误删了,能通过其他节点同步过来吗

### ISSUE THREAD

**Issue by dengjin001** [blockchain-jd-com/jdchain#17]
如题，区块数据是存入的redis还是有本地文件存储，误删的数据能通过什么办法同步回来

**Comment by huanghaiquan** [comment]
账本数据全部都在 Storage 中，如果选择是 Redis 的话。
“自动进行账本数据同步”的特性正在开发中，目前可以手动地从其它节点的redis库复制一份即可。
