### ISSUE TITLE
getTransactionByContentHash方法报404

### ISSUE THREAD

**Issue by dengjin001** [blockchain-jd-com/jdchain#18]
bcsrv.getTransactionByContentHash 方法debug 发现request 的url和api文档中的不一样
![image](https://user-images.githubusercontent.com/29300542/58845994-05222280-86b0-11e9-99de-e5cb30533149.png)
![image](https://user-images.githubusercontent.com/29300542/58846006-166b2f00-86b0-11e9-8dc3-8ddfe8606d1c.png)

**Comment by dengjin001** [comment]
![image](https://user-images.githubusercontent.com/29300542/58846020-2e42b300-86b0-11e9-904e-2e4a0c098e50.png)

**Comment by shaozhuguang** [comment]
@dengjin001  感谢您的反馈，我们会尽快对API文档内容进行调整~
