### ISSUE TITLE
压测后报The accessing index is out of BytesSlice's bounds!

### ISSUE THREAD

**Issue by dengjin001** [blockchain-jd-com/jdchain#19]
转账压测后在进行任何写数据操作都报这个错
![image](https://user-images.githubusercontent.com/29300542/59336059-6e4d0a00-8d30-11e9-93ae-723ddefd89c8.png)
![image](https://user-images.githubusercontent.com/29300542/59336100-7c9b2600-8d30-11e9-9a0e-3cb5b49958ce.png)

**Comment by huanghaiquan** [comment]
这段 Gateway 的日志信息太少尚不足以确诊问题，您可以把包括 Peer 在内的更多日志信息也一起发到我们的支持邮箱 jdchain-support@jd.com ，我们会跟您联系。
祝好～
