### ISSUE TITLE
package com.jd.blockchain.utils.web.server not found

### ISSUE THREAD

**Issue by terasum** [blockchain-jd-com/jdchain#2]
When Running the `test/perf/com/jd/blockchain/consensus/node/WebBooter.java` 

It raised:

```
Error:(27, 42) java: package com.jd.blockchain.utils.web.server not exists
```

does it be omitted?

**Comment by shaozhuguang** [comment]
@terasum 

Thank you for your feedback.

This class is currently problematic for unit testing, but is no longer used.

We will delete it in the next version.
