### ISSUE TITLE
请教jd chain 怎么连接rocksdb的？ 

### ISSUE THREAD

**Issue by javadoge** [blockchain-jd-com/jdchain#22]
根据配置文件示例，提到 rocksdb0.db，我在 rocksdb 编译后 也没发现这个  db后缀的文件，关于rocksdb 相关的东西  文档能说详细一点么？

**Comment by javadoge** [comment]
有没有交流的社区呢？除了这里发 issues

**Comment by zhaoGuangwei** [comment]
rocksdb对应应用者来说是透明的，只要配置文件配置上就可以。rocksdb0.db就是事先您定义的一个文件夹。这个文件夹会在执行ledger-init.sh初始化完成之后产生内容。如果仍有问题，可以直接给我们发邮件：jdchain-support@jd.com。在mail中可以介绍一下自己，留个微信，方便我们直接跟您沟通。
