### ISSUE TITLE
service.getTransactionCount(ledgerHash，blockhash or blockheight)的实现很奇怪

### ISSUE THREAD

**Issue by bjzhaoxy** [blockchain-jd-com/jdchain#23]
从传入的参数以及名字，按我的理解，应该是返回某个区块包含的交易数量，实际测试发现返回的是某个区块以及之前所有区块的交易总数量，感觉有点奇怪，而且这个数量用到的场景多嘛，感觉不如返回单一区块包含的数量有用。

**Comment by huanghaiquan** [comment]
抱歉，我们的回复迟到了。
此接口之所以这样实现，一方面是方便获得全局交易数量的统计结果，目前区块链浏览器中显示的交易总数即来源于此；另一方面，也跟账本结构的设计有关，即从某个区块出发总是得到全局状态，这个更常用，通常情况应用很少会关注单个区块的变化。
另外，如果您想要获取单个区块的交易数量，可以前后两个区块的交易总数相减即可。
希望我的回答可以帮到您。
