### ISSUE TITLE
非代码问题，官网示例错误

### ISSUE THREAD

**Issue by tianliang211** [blockchain-jd-com/jdchain#25]
示例页面

http://ledger.jd.com/codeexample.html

其中
public static BlockchainKeyPair CLIENT_CERT = BlockchainKeyGenerator.getInstance().generate();

有误，引用类为BlockchainKeypair，其中pair的p应为小写，引用自com.jd.blockchain.ledger.BlockchainKeypair。示例中的代码会报找不到类

**Comment by zhaoGuangwei** [comment]
你这个问题反馈的很对，多谢！
国庆节前刚刚献礼，上了一把新版本，有些细节还得好好再完善，我这就着手修改。京东JDChain感谢您的持续关注，希望您继续提出宝贵意见，多谢！
