### ISSUE TITLE
初始化账本疑问

### ISSUE THREAD

**Issue by jy1989** [blockchain-jd-com/jdchain#27]
根据文档所说，初始化账本需要至少4个peer，最后生成出 ledger-binding.conf
但是启动peer又需要 ledger-binding.conf

所以是先初始化账本还是先启动peer先呢？

另：peer-1.1.0.RELEASE程序中 有manager-startup.sh启动后有个区块链工具，打开看到有公私钥管理、账本管理的界面。 看样子也能用来初始化账本，但文档中未见提及，请问这个工具有使用文档吗？

![image](https://user-images.githubusercontent.com/1291756/67664898-83ef6300-f9a3-11e9-9ac5-088b25d2f769.png)

**Comment by zhaoGuangwei** [comment]
微信公众号“京东智臻链”有官方的工具使用说明：https://mp.weixin.qq.com/s/vyhcMBbICywMBCUgkEiAug，后来ledger.jd.com推出了正式版，我做了适当修改，具体可参考这个文章：https://3.cn/ucKrBFMUv。如仍有疑问，可给jdchain-support@jd.com发送邮件，告知微信号，我们提供一对一的服务。谢谢您对JDChain的关注。

**Comment by jy1989** [comment]
> 微信公众号“京东智臻链”有官方的工具使用说明：https://mp.weixin.qq.com/s/vyhcMBbICywMBCUgkEiAug ，后来ledger.jd.com推出了正式版，我做了适当修改，具体可参考这个文章：https://3.cn/ucKrBFMUv 。如仍有疑问，可给[jdchain-support@jd.com](mailto:jdchain-support@jd.com)发送邮件，告知微信号，我们提供一对一的服务。谢谢您对JDChain的关注。

感谢，看了一下，网站下载的peer-1.1.0.RELEASE 和微信文章的说明稍微有点出入的。
还是有几个点没明白：

1. 初始化账本节点信息中两个地址分别是什么意思？ 我理解其中一个就是自己peer的地址，另一个是协调方的地址？
![image](https://user-images.githubusercontent.com/1291756/67667686-4d1c4b80-f9a9-11e9-9707-586a1e219f95.png)

那协调方配置的时候两个地址不是应该一样的么？

2. 另外如果用redis数据库，配置该怎样写呢？
![image](https://user-images.githubusercontent.com/1291756/67667727-68875680-f9a9-11e9-8b80-1c53aac062af.png)

3. 如果不使用界面，使用 `./ledger-init.sh` 初始化账本的话，是先初始化账本还是先启动peer呢？
正如问题中述，初始化账本要peer，但是启动peer又需要 ledger-binding.conf

**Comment by zhaoGuangwei** [comment]
1.你这个问题提的很好，“peer节点地址”写得还是有歧义，这个指：peer节点共识地址。
2.redis可以参照部署文档填写，格式为：
#账本数据库的连接字符，下为rocksdb样例
#rocksdb数据库连接格式：rocksdb://{path}
#redis数据库连接格式：redis://{ip}:{prot}/{db}
3.如果脚本操作，可参考部署文档，要先初始化，生成ledger-binding.conf文件，再启动peer。

**Comment by zhaoGuangwei** [comment]
协调方地址：就是协调管理方的地址，各个peer的信息都会发送给协调方；
共识节点信息：peer之间需要共识，如果是单机，只能靠不同端口来共识；
初始化共识地址：默认端口22000，这只是针对初始化节点使用的共识端口。如果初始化完毕之后，此端口不再使用。peer节点的常规共识阶段，采用“共识节点信息”中标注的端口。

**Comment by zhaoGuangwei** [comment]
我更新了一下让你下载的文档，采用了最新的界面截图，可以参考一下：https://3.cn/udOGWEWp4

**Comment by jy1989** [comment]
> 协调方地址：就是协调管理方的地址，各个peer的信息都会发送给协调方；
> 共识节点信息：peer之间需要共识，如果是单机，只能靠不同端口来共识；
> 初始化共识地址：默认端口22000，这只是针对初始化节点使用的共识端口。如果初始化完毕之后，此端口不再使用。peer节点的常规共识阶段，采用“共识节点信息”中标注的端口。

好的，意思是初始化共识地址是给单机时候用到，那单机的话要分配不同的端口让其初始化？

另外根据文档看来，如果peer增加一个，那所有之前peer的配置信息都要修改吗？比如说一开始有4个peer，增加一个，前4个都要修改配置？  再增加一个，前5个都要修改配置？ 这样理解对吗？

**Comment by zhaoGuangwei** [comment]
初始化共识地址，单机多机都会用到，但是单机必须采用不同端口。
通过界面的方式初始化，你在一开始的时候就设置好节点个数即可。如果后续再增加新节点，需要采用动态新增加peer的接口，这个需要额外的操作。初期可以一开始的时候就定义好。
你的理解是对的，因为新增加一个peer，原先每个peer的配置都要包含这个新peer的信息，所以需要修改。

**Comment by jy1989** [comment]
经过配置  成功进入到安装进度，但卡在了 check ledger inits status
![image](https://user-images.githubusercontent.com/1291756/67736394-6e7d4600-fa42-11e9-88d5-31cfa1d9b0af.png)

**Comment by jy1989** [comment]
另外这个
![image](https://user-images.githubusercontent.com/1291756/67736442-a71d1f80-fa42-11e9-8dd6-c55b7ad9df8d.png)
协调方地址指的是 协调方区块链管理工具的地址吧？
