### ISSUE TITLE
代码开源疑问

### ISSUE THREAD

**Issue by michaelmao999** [blockchain-jd-com/jdchain#28]
我刚刚拉下代码，但有三个依赖库maven获取不到，是不是没有开源？
com.jd.blockchain:bft-smart
com.jd.blockchain:data-explorer
com.jd.blockchain:manager-explorer

**Comment by zhaoGuangwei** [comment]
你用父节点就可以看到其他几个工程的列表，https://github.com/blockchain-jd-com 
其中data-explorer和manager-explorer都整合到explorer工程中。感谢您对JDChain的关注。

**Comment by michaelmao999** [comment]
多谢，我修复了一些编译版本问题支持最新的1.1.1，现在可以编译成功了
