### ISSUE TITLE
最新的版本：jdchain-peer-1.1.1.RELEASE.zip目录/bin下没有jump-start.sh的脚本文件了

### ISSUE THREAD

**Issue by andaywgz** [blockchain-jd-com/jdchain#30]
参考文档：从零开始部署JDChain，对应的安装包是：jdchain-peer-1.1.0-xxx.zip，我下载了最新的版本1.1.1，但是里边没有对应的jump-start.sh脚本文件了，请问这种方式是抛弃了吗?还是忘记放了

**Comment by zhaoGuangwei** [comment]
最新的1.1.1.RELEASE，规范了一下名字，用manager-startup.sh来代替了。抱歉啊，对外发布的公众号文章，不便于修改了。

**Comment by andaywgz** [comment]
好的，收到，多谢了哈

**Comment by andaywgz** [comment]
回复消息很及时，666
