### ISSUE TITLE
执行[./ledger-init.sh]报错--

### ISSUE THREAD

**Issue by andaywgz** [blockchain-jd-com/jdchain#31]
Start consensus with each other participant...
com.jd.blockchain.utils.http.HttpServiceException: Connect to 127.0.0.1:8810 [/127.0.0.1] failed: Connection refused (Connection refused)
	
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:8820 [/127.0.0.1] failed: Connection refused (Connection refused)

有点疑惑，这个脚本我理解的只是生成ledger-binding.conf文件用的，怎么会尝试连接账本初始的服务哪。。

**Comment by zhaoGuangwei** [comment]
初始化阶段，也有个初始化共识的过程，需要生成创世区块。感谢您对JDChain的关注。

**Comment by andaywgz** [comment]
感谢，这个问题怎么解决哪？
在运行ledger-init.sh脚本之前，我需要怎么启动服务哪？

**Comment by andaywgz** [comment]
按照馆方的文档说明，我刚完成了2.3.1 初始化配置，现在按照2.3.2在操作
