### ISSUE TITLE
是要在环境中预先安装rocksdb吗？

### ISSUE THREAD

**Issue by dddengyunjie** [blockchain-jd-com/jdchain#32]
执行mvn clean package报错了

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
21.0:test (default-test) on project storage-rocksdb: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\dengyj\workspace\go\src\github.com\blockchain-j
d-com\jdchain\source\storage\storage-rocksdb\target\surefire-reports for the ind
ividual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].
dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

**Comment by zhaoGuangwei** [comment]
如果你想使用开发环境，依赖的explorer项目和bftsmart项目，需要先编译至本地仓库。然后执行：mvn clean install -DskipTests=true。

**Comment by zhaoGuangwei** [comment]
rocksdb是内嵌的，你无需关心。 如果忽略测试能跑通，再考虑单元测试的问题。

**Comment by dddengyunjie** [comment]
> 如果你想使用开发环境，依赖的explorer项目和bftsmart项目，需要先编译至本地仓库。然后执行：mvn clean install -DskipTests=true。

那两个依赖都是安装成功的，现在执行mvn clean package碰到了另一个错误：
[INFO] storage-composite .................................. SUCCESS [  0.305 s]
[INFO] gateway ............................................ FAILURE [  0.166 s]
[INFO] tools-initializer .................................. SKIPPED
[INFO] peer ............................................... SKIPPED
[INFO] manager ............................................ SKIPPED
[INFO] manager-model ...................................... SKIPPED
[INFO] manager-service .................................... SKIPPED
[INFO] manager-web ........................................ SKIPPED
[INFO] manager-booter ..................................... SKIPPED
[INFO] sdk-samples ........................................ SKIPPED
[INFO] tools-keygen-booter ................................ SKIPPED
[INFO] tools-initializer-booter ........................... SKIPPED
[INFO] test ............................................... SKIPPED
[INFO] test-consensus-client .............................. SKIPPED
[INFO] test-consensus-node ................................ SKIPPED
[INFO] test-ledger ........................................ SKIPPED
[INFO] test-integration ................................... SKIPPED
[INFO] deployment ......................................... SKIPPED
[INFO] deployment-gateway ................................. SKIPPED
[INFO] deployment-peer .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:33 min
[INFO] Finished at: 2019-11-10T18:34:08-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project gateway: Could not resolve dependencies for project com.jd.blockchain:gateway:jar:1.2.0-SNAPSHOT: Failure to find com.jd.blockchain:data-explorer:jar:1.1.0.RELEASE in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :gateway

能帮忙分析下这个怎么解决吗？我对java不熟悉啊

**Comment by zhangshuang01** [comment]
您好：
        针对上面的问题，[INFO] gateway ............................................ FAILURE [ 0.166 s]，失败原因是您没有在本地安装data-explorer:jar:1.1.0.RELEASE这个包，注意是1.1.0。先在本地安装这个包，使用命令mvn clean install即安装到了本地，然后再重新编译JD Chain项目，如果再遇到别的问题咱们再看。

**Comment by zhangshuang01** [comment]
您好：
      针对您最初提的project storage-rocksdb: There are test failures. 这个问题，我发现您用的是Windows系统，很抱歉我们平时开发都是在MAC中，所以没有及时感知到您提出的问题。在Windows系统中确实存在这样的现象，您可以通过以下代码修改先暂时解决编译问题，待我们下个版本会把这个问题解决掉！
修改1：RocksDBConnectionFactory类：把原来的connect方法用新的替换掉。
@Override
	public synchronized DbConnection connect(String dbConnectionString, String password) {
		if (!dbConnectionString.startsWith(URI_SCHEME + "://")) {
			throw new IllegalArgumentException("Illegal format of rocksdb connection string!");
		}
		//skip rocksdb://
		String dbPath = dbConnectionString.substring(10);

		RocksDBConnection conn = connections.get(dbPath);
		if (conn != null) {
			return conn;
		}

		Options options = initOptions();

		conn = new RocksDBConnection(dbPath, options);
		connections.put(dbPath, conn);

		return conn;
	}
修改2：同一个类，修改initOptions方法：
把compressionLevels.add(CompressionType.NO_COMPRESSION); // 0-1
compressionLevels.add(CompressionType.SNAPPY_COMPRESSION); // 1-2
compressionLevels.add(CompressionType.SNAPPY_COMPRESSION); // 2-3
compressionLevels.add(CompressionType.SNAPPY_COMPRESSION); // 3-4
compressionLevels.add(CompressionType.SNAPPY_COMPRESSION); // 4-5
compressionLevels.add(CompressionType.SNAPPY_COMPRESSION); // 5-6
compressionLevels.add(CompressionType.SNAPPY_COMPRESSION); // 6-7
中的SNAPPY_COMPRESSION替换成NO_COMPRESSION。
