### ISSUE TITLE
gateway启动报错-The specified file is not a private key file!

### ISSUE THREAD

**Issue by andaywgz** [blockchain-jd-com/jdchain#33]
网关启动报错了，错误信息如下：
Starting web server......
Error!! The specified file is not a private key file!

从错误信息来看，是private key file 设置的问题，但是我没有设置private key的文件路径，直接设置了key，具体如下：

#默认公钥的内容（Base58编码数据）；
keys.default.pubkey=3snPdw7i7PZKQFkED2uFeeTNxYoBQv5NgnyvySgYzCS54pri2UtoUy
#默认私钥的路径；在 pk-path 和 pk 之间必须设置其一；
keys.default.privkey-path=
#默认私钥的内容（加密的Base58编码数据）；在 pk-path 和 pk 之间必须设置其一；
keys.default.privkey=3snPdw7i7PiGQLK2bp5VqzDnqrSrwKSd8TpAcLDv4cQzWj3Nq7ba6R
#默认私钥的解码密码；
keys.default.privkey-password=Ej2nZUzgdhqzQAp68CadTa4DMLKeNN69YHhGty2wpqbF

**Comment by zhaoGuangwei** [comment]
老铁，你看看你的privkey是不是有点瑕疵？按说privkey都是以177打头的。

**Comment by andaywgz** [comment]
是的，已经解决了，目前可以启动了，但是出现了另外一个问题，如下：
Start connecting to peer ....

Peer[127.0.0.1:7080] is connected success!

Peer[127.0.0.1:7080] is connected success!

17:16:00.007 ERROR com.jd.blockchain.gateway.web.GatewayTimeTasks 43 updateLedger - This gateway has not connected to a peer, please connect it first!!!

17:16:25.573 ERROR com.jd.blockchain.gateway.web.GatewayGlobalExceptionHandler 34 json - Unexpected exception occurred! --[RequestURL=[GET] http://127.0.0.1:8081/ledgers][class java.lang.IllegalStateException]Peer connection was closed! java.lang.IllegalStateException: Peer connection was closed!

**Comment by zhaoGuangwei** [comment]
]Peer connection was closed! 你确保四个peer已经正常启动了吗？看看后台是不是有问题，是不是都是使用了7080的端口，没有进行修改？

**Comment by andaywgz** [comment]
已经搞定了，总结下，总共碰到了两个问题：
1、端口问题
需要在peer启动脚本peer-starup.sh里，修改下启动端口，避免重复，分别为：7080，7081，7082，7083【peer如果部署在不同的机器或容器里，请忽略】

2、gateway配置gateway.conf问题
keys.default.pubkey，keys.default.privkey，这两个key配置有问题
这两个key，从任意一个peer中获取即可
错误原因：一开始我是直接从生成的conf/keys/*.priv,pub两个文件中获取填入的
正确做法：从管理页面--> 公私钥管理里获取，如下：
![image](https://user-images.githubusercontent.com/1032130/68486475-146b5480-027c-11ea-9cee-06067b7522a3.png)

问题分析：
建议再完善下文档，因为按照文档的指导，是容易忽略这两个地方的配置的

我的疑惑：
为什么peer节点对应config/keys下生成的priv，pub秘钥和管理页面看到的不一样，而且秘钥文件里的私钥，和页面里显示的公钥值一样，有点不太明白其中的逻辑管理
秘钥文件：
priv：3snPdw7i7PiGQLK2bp5VqzDnqrSrwKSd8TpAcLDv4cQzWj3Nq7ba6R
pub：3snPdw7i7PZKQFkED2uFeeTNxYoBQv5NgnyvySgYzCS54pri2UtoUy

页面显示：
priv：177gjtApqRzjpUJ9NqrpGvDBh7ju3SZr4ywp8pRLNKif8y9ucEy9AvBMfUryziZJKx2rS2P
pub：3snPdw7i7PiGQLK2bp5VqzDnqrSrwKSd8TpAcLDv4cQzWj3Nq7ba6R

**Comment by michaelmao999** [comment]
生成的密钥文件里面就是正确的，私钥 177打头， 公钥 3sn打头

**Comment by zhaoGuangwei** [comment]
你说的对，有个文字笔误当时没有更正过来。下次我们修正。我看您做事很细心，您方便把您的操作流程和使用心得写个详细的使用文档吗？我把它放到starter工程中，方便其它的初学者快速上手。当然，我们也会尽快同步完善我们其它的使用文档。希望初学者能够通过不同角度的使用文档，来快速上手。再次感谢您对JDChain的支持。

**Comment by andaywgz** [comment]
![image](https://user-images.githubusercontent.com/1032130/68528867-25c36800-0333-11ea-8781-a5fb48d9008e.png)
![image](https://user-images.githubusercontent.com/1032130/68528876-44c1fa00-0333-11ea-809d-d3b87a1bb0b1.png)
我看了下，priv文件里的是不对的，bak里的文件是对的
【其他peer的情况同样是这样】

**Comment by andaywgz** [comment]
@zhaoGuangwei 好的，我更新下文档
