### ISSUE TITLE
prepTx.commit() 报错：The accessing index is out of BytesSlice's bounds

### ISSUE THREAD

**Issue by michaelmao999** [blockchain-jd-com/jdchain#34]
执行SDKDemo_User示例代码时，peer节点报错：
There is no transaction in the current block, and no empty blocks is allowed.

其返回给gateway空。
![PeerException](https://user-images.githubusercontent.com/43536056/68522847-57b0dc00-02eb-11ea-8313-47080a753f04.JPG)

**Comment by zhaoGuangwei** [comment]
这个可能是由于公私钥使用不符导致的，您再检查看看？

**Comment by michaelmao999** [comment]
peer, gateway都是正常启动，SDKDemo_User示例代码执行报错， 使用的是1.1.1最新版本

**Comment by zhaoGuangwei** [comment]
最近有很多用户反馈这个问题，可能是操作不当导致的。我完善了一下相关文档和视频资料，大家可以参考：
1）https://github.com/blockchain-jd-com/jdchain-starter/tree/master/doc 中“从零开始部署JDChain”；
2）操作视频：https://3.cn/TDtyTS4Ze （下载JDChain1.1.1.RELEASE版本的文件，最好同步下载字幕）

感谢您对JDChain的关注！

**Comment by michaelmao999** [comment]
所有的Peer和Gateway正常启动，是否可以说明我的部署是正确？ 
当我修改gateway代码（GatewayServerBooter）执行示例代码，也不行，只是peer节点不报错，只是返回空， 但没有任何数据产生。
ConsoleUtils.info("\r\n\r\nStart connecting to peer ....");
		BlockBrowserController blockBrowserController = appCtx.getBean(BlockBrowserController.class);
		blockBrowserController.setDataRetrievalUrl(config.dataRetrievalUrl());
		blockBrowserController.setSchemaRetrievalUrl(config.getSchemaRetrievalUrl());
		PeerConnector peerConnector = appCtx.getBean(PeerConnector.class);

        peerConnector.connect(config.masterPeerAddress(), defaultKeyPair, config.providerConfig().getProviders());
		if (peerConnector instanceof PeerConnectionManager) {
			PeerConnectionManager peerService = (PeerConnectionManager) peerConnector;
			TransactionService transactionService = peerService.getTransactionService();
			BlockchainService blockchainService = peerService.getBlockchainService();
			HashDigest[] ledgerHashs = blockchainService.getLedgerHashs();
			HashDigest ledgerHash = ledgerHashs[0];
			TransactionTemplate txTemp = blockchainService.newTransaction(ledgerHash);
			BlockchainKeypair adminKey = new BlockchainKeypair(defaultKeyPair.getPubKey(), defaultKeyPair.getPrivKey());
			TransactionResponse response = TransactionRequestTester.registerUser(txTemp, adminKey);

		}

    public static TransactionResponse registerUser(TransactionTemplate txTemp, BlockchainKeypair adminKey) {

        txTemp.users().register(dataAccount.getIdentity());
        // TX 准备就绪；
        PreparedTransaction prepTx = txTemp.prepare();
        prepTx.sign(adminKey);

        // 提交交易；
        TransactionResponse response  = prepTx.commit();
        return response;
    }

**Comment by zhaoGuangwei** [comment]
你先用jdchain-starter项目中的SDKTest.java的insertData()来验证一下。这个是我常用的测试类，里面改动相对较少。这个成功了之后，可以再看一些复杂的样例。这个测试类我在操作视频：https://3.cn/TDtyTS4Ze 的结尾有演示。你修改一下IP/PORT/公私钥的基本信息就可以使用。 如果还有问题，给jdchain-support.jd.com发邮件，简单介绍一下自己，写上微信，我给你一对一支持。

**Comment by michaelmao999** [comment]
我把SDKDemo_Constant.PUB_KEY/PRIV_KEY 修改成网关的公私钥后，就可以正常运行了。 为了不让大家犯同样的错误，我修改公私钥名字增加了前缀GW_并已经提交了一个PR，请帮忙reveiw.
https://github.com/blockchain-jd-com/jdchain-starter/pull/6
