### ISSUE TITLE
peer和gateway的健壮性

### ISSUE THREAD

**Issue by jy1989** [blockchain-jd-com/jdchain#35]
情况如下：
sdk里先用正确的公私钥去操作是没问题的，但假如换了一个不属于任何节点的公私钥，peer会报错，gw会超时：

![image](https://user-images.githubusercontent.com/1291756/68912263-9c78bf00-0792-11ea-87da-08e533b7b281.png)

这时换回正常的公私钥去操作gw也会一直超时的。 peer好像恢复不过来。

而且好像不止这种情况，例如向错误的地址commit数据，只要是sdk里参数不正确，导致peer异常了，之后网关就会一直超时操作不了了。目前只能通过重启peer和gw来解决。

**Comment by zhaoGuangwei** [comment]
非常感谢您的反馈。这个问题我们最近跟踪一下。上周事情比较多，没来得及看issue，抱歉。
