### ISSUE TITLE
初始化账本 一直卡在走‘Check LedgerInit's Status ....’没有出现完成

### ISSUE THREAD

**Issue by tangruojin** [blockchain-jd-com/jdchain#36]
初始化账本不报错也没成功一直状态如下
Execute LedgerInit's Command -> SUCCESS

1 Check LedgerInit's Status ......
2 Check LedgerInit's Status ......
3 Check LedgerInit's Status ......
。。。。。。。
N Check LedgerInit's Status ......
**按照视频中配置，视频里是直接跳过了这块，请问是哪里的问题（一直在检查没有停止2小时了）
1.1.1版本**
请教下事哪里配置或是出现了问题，是在同一台机器上配置的。
服务器也未爆出异常。

**Comment by zhang303991940** [comment]
这个我也遇到了啊，初始化账本没过去。不知道怎么回事。视频教程和文档都没有具体描述，点击“开始”按钮就直接没反映了。过了一会在“查看账本”菜单里边什么也没有。

**Comment by michaelmao999** [comment]
建议你们尝试一下手工执行方式

**Comment by zhaoGuangwei** [comment]
点击开始，需要四个同时执行。如果没反应，看看本机内存释放够用。
如果如下操作还有问题，联系：jdchain-support@jd.com，告知微信，直接处理。
我完善了一下相关文档和视频资料，大家可以参考：
1）先kill掉JDChain相关进程，centos下命令为：ps -ef|grep 'jdchain'|grep -v grep|cut -c 9-15|xargs kill -9
2）https://github.com/blockchain-jd-com/jdchain-starter/tree/master/doc 中“从零开始部署JDChain”；
3）操作视频：https://3.cn/TDtyTS4Ze （下载JDChain1.1.1.RELEASE版本的文件，最好同步下载字幕）
