### ISSUE TITLE
执行合约中是否能获取到交易hash值

### ISSUE THREAD

**Issue by dengjin001** [blockchain-jd-com/jdchain#38]
通过TransactionTemplate.contract(contractAddress, Contract.class) 来调用合约，想要把截图中的交易hash存在数据账号的值里面

![image](https://user-images.githubusercontent.com/29300542/69858840-d9ce6800-12cd-11ea-941d-f274119ae07a.png)

**Comment by zhaoGuangwei** [comment]
邓总您好，根据代码逻辑，这个时候还没有生成contentHash，所以无法提前处理。
相关代码可参考：
public TransactionContent prepareContent(long time) {
		TxContentBlob txContent = new TxContentBlob(ledgerHash);
		txContent.addOperations(opFactory.getOperations());
		txContent.setTime(time);

		HashDigest contentHash = computeTxContentHash(txContent);
		txContent.setHash(contentHash);

		return txContent;
	}
可以通过TransactionResponse获得对应的contentHash。
