### ISSUE TITLE
Failed to execute bash script files  

### ISSUE THREAD

**Issue by lesterli** [blockchain-jd-com/jdchain#4]
> jd@ubuntu:~/jdchain/bin$ ./keygen.sh -n jd-com
> bash: ./keygen.sh: /bin/bash^M: bad interpreter: No such file or directory

These script files are with **Windows format ( CR LF )**, should be convert to **Unix format ( LF )**.

**Comment by zhaoGuangwei** [comment]
Thank you for your reminder. We will fix this problem in the future.

**Comment by zhaoGuangwei** [comment]
新版本完善，多谢
