### ISSUE TITLE
rockdb starts abnormally under Windows

### ISSUE THREAD

**Issue by klboke** [blockchain-jd-com/jdchain#40]
Windows10系统，rocksdb初始化抛如下异常：

org.rocksdb.RocksDBException: Compression type Snappy is not linked with the binary.
	at org.rocksdb.RocksDB.open(Native Method)
	at org.rocksdb.RocksDB.open(RocksDB.java:286)
解决方案：
升级到rocksdb.version到5.18.3问题解决
另jraft中的rocksdb版本也是升级到了这个版本：https://github.com/sofastack/sofa-jraft/blob/master/pom.xml#L76

**Comment by zhaoGuangwei** [comment]
已经升级为：<rocksdb.version>6.3.6</rocksdb.version>，感谢您的参与！
