### ISSUE TITLE
网关高级检索时报grpc异常：wrong wireType = 2 for field StartTs  (chain/web)[0167]

### ISSUE THREAD

**Issue by klboke** [blockchain-jd-com/jdchain#41]
综合查询如：
![image](https://user-images.githubusercontent.com/18591662/70486629-80680380-1b2d-11ea-9416-148d65aa5ea4.png)
argus抛grpc异常如下：
```
 **** While try to query failed: rpc error: code = Internal desc = grpc: error unmarshalling request: proto: wrong wireType = 2 for field StartTs  (chain/web)[0167]
[GIN] 2019/12/10 - 09:10:42 | 200 |     524.254µs |       127.0.0.1 | GET      /ledgers/j5jiskfAxuxq8Jf21Huz59mnHvHmLKkm5zp2MevSBdPuBu/all/search?keyword=123456
```
另argus源码是闭源的么

**Comment by zhaoGuangwei** [comment]
argus是有关高级检索的另外一个项目，如果感兴趣，可以部署一下：http://ledger.jd.com/argus.html
目前argus这个功能还处于试验阶段，尚未准备好，所以目前暂时只提供可执行的程序包。后续如果有问题，可以给我们的技术支持邮箱：jdchain-support@jd.com发邮件。看您提出的几个issue，技术分析能力很强。再次感谢您对JDChain的关注！

**Comment by klboke** [comment]
嗯，上面的异常是部署好argus后，网关通过rest api访问时，argus日志里的异常。部署时，argus schema-update 是正常的，这个异常看上去像grpc序列化问题，因为没有源码所以没法准确定位问题，希望官方可以看下

**Comment by zhaoGuangwei** [comment]
gateway.conf中的这些参数都配置了吗？
#数据检索服务对应URL，格式：http://{ip}:{port}，例如：http://127.0.0.1:10001
#若该值不配置或配置不正确，则浏览器模糊查询部分无法正常显示
#数据检索服务模块（Argus）需单独部署，若不部署其他功能仍可正常使用
data.retrieval.url=http://127.0.0.1:10001
schema.retrieval.url=http://192.168.151.40:8082

如果仍有问题，可以加我微信，及时沟通：10696699.

**Comment by klboke** [comment]
都已配置，可确认请求已正确发送到argus服务，因为如果在搜索框输入长度为1的字符，argus会正常响应提示查询字符串太短

**Comment by imuge** [comment]
粗略排查，`argus`集成`dgraph 1.1`及以上会抛以上异常，我选择`v1.0.18-rc4`运行成功了：

##  DGraph

1. Run dgraphzero
```bash
docker run -it -p 5080:5080 -p 6080:6080 -p 8080:8080 -p 9080:9080 -p 8000:8000 -v /home/liuyuanmu/Softs/docker/dgraph/data:/dgraph --name dgraph dgraph/dgraph:v1.0.18-rc4 dgraph zero
```

2. In another terminal, now run dgraph
```bash
docker exec -it dgraph dgraph alpha --lru_mb 2048 --zero localhost:5080
```

## Argus

1. scheme
```bash
argus schema-update  --dgraph 127.0.0.1:9080
```

2. api
```bash
nohup argus api-server --host 127.0.0.1 --port 10001 --dgraph 127.0.0.1:9080 --production true> api-server.out 2>&1 &
```

3. task
```bash
nohup argus task --port 10005 --dgraph 127.0.0.1:9080 > task_monitor.log 2>&1 &
```

4. ledger
```bash
nohup argus ledger-rdf --api 127.0.0.1:8081 --dgraph 127.0.0.1:9080 > converter.log 2>&1 &
```

5. data
```bash
nohup argus data --port 8082 --ledger-host http://127.0.0.1:8081 --dgraph 127.0.0.1:9080 --production true > value_indexer.out 2>&1 &
```

6. drop
```bash
argus drop  --dgraph 127.0.0.1:9080
```
@klboke

**Comment by klboke** [comment]
@imuge 我试了下，确实是版本的问题，应该和我之前的猜想的原因符合，默认使用下面的脚本：
```
curl https://get.dgraph.io -sSf | bash
```
安装的dgraph版本和argus服务里使用的go dgraph客户端版本不匹配导致的grpc通讯序列化的问题。
但是argus部分的代码现在未开源，无从查证。 @zhaoGuangwei 有时间看下呀

**Comment by zhaoGuangwei** [comment]
目前Dgraph version   : v1.0.16。前几天针对最新的JDChain1.1.2.RELEASE版本，完善了穿透式检索的接口调用逻辑。乐观估计：明天会推出jdchain-argus-0.8.4.RELEASE.zip版本。具体可留意jdchain官网：ledger.jd.com，或者知乎主页：https://www.zhihu.com/people/jdchain。 感谢关注！
