### ISSUE TITLE
初始化账本，交易许可失败：Invalid permission from participant

### ISSUE THREAD

**Issue by klboke** [blockchain-jd-com/jdchain#45]
### 环境：
共识提供者采用RabbitMQ，使用ledger-init.sh脚本初始化账本时输出如下信息，账本创建失败

### 说明：
在请求其它参与方的账本创建许可时，输出如下异常：
```
Invalid permission from participant! --[Id=LdeNn8bWuc2DaqAbx3XCQPUf7bdb94PTKFT2E][name=node1.com]
Invalid permission from participant! --[Id=LdeNezcG3rhs31u8UBSwvfMf2BKr1ZkaLKJAG][name=node2.com]
Invalid permission from participant! --[Id=LdeNqxGmBdmEZK6hVeLcnXppW2qnLLKMMiQhN][name=node3.com]
```
`看到这个输出，就代表可以排除公私钥的问题的。因为这个是最后一步许可，交易哈希许可签名验证失败输出的。而交易哈希是根据当前账本上下文创建的，当前账本上下文是根据初始化账本配置装载的，所以最后的问题出在初始化账本的配置上面。我是因为理解错了下面的配置：
```
# 当前账本交易发送队列主题（不同账本需不同主题）
system.msg.queue.topic.tx=node3-topic
```
误以为每个节点的交易队列需要不同主题，导致了每个节点加载的账本不一致，从而导致了上面的交易签名验证失败

### 解决
初始化账本时一般包含三个配置文件，账本配置 ledger.init，本地节点配置：local.conf ，共识服务配置:bftsmart.config 或mq.config ,其中共识服务配置是包含在账本配置ledger.init里被加载的，所以
初始化一个区块链账本需要保证 每个节点的【账本配置 + 共识服务配置 】一模一样。才能保证交易签名哈希一致

**Comment by zhaoGuangwei** [comment]
是的，分析的很到位！
