### ISSUE TITLE
共识节点的外网ip

### ISSUE THREAD

**Issue by jy1989** [blockchain-jd-com/jdchain#47]
从最简单的部署模型来说，需要
![image](https://user-images.githubusercontent.com/1291756/71237964-e0388880-233d-11ea-9e3f-4814781be964.png)

1个网关和4个节点，节点通过共识算法保持数据一致。 网关配置了4个节点中某一个信息（某个节点的外网或内网ip）。

假设后面加入了独立的第5个节点，第5个节点是否需要一个外网可访问的ip？  第5个节点通过网关找到前4个节点之后，假如前4个节点只能够通过内网互相访问，那第5个节点是怎样进行共识的？

还是说所有节点都必须配备一个外网ip？

**Comment by klboke** [comment]
目前的模式，在已经共识过的在运行的区块节点之外，新增第五个节点非常困难，几乎不可操作

**Comment by jy1989** [comment]
> 目前的模式，在已经共识过的在运行的区块节点之外，新增第五个节点非常困难，几乎不可操作

怎么说？  我看到例子已经有了呀  

https://github.com/blockchain-jd-com/jdchain-starter/blob/master/contract-starter/src/test/java/com/jd/blockchain/SDK_GateWay_Participant_Test_.java

**Comment by klboke** [comment]
这个还没看到，有待验证。假如像你上面描述这样，肯定需要一个和peer节点相互通讯的ip和端口，如果是基于RabbitMQ的共识的的话另说

**Comment by zhaoGuangwei** [comment]
是的，目前新增节点还是半自动的方式，没有实现全自动。两位感兴趣，可以看看：https://3.cn/CagJrfM
