### ISSUE TITLE
节点发现机制

### ISSUE THREAD

**Issue by qq511340079** [blockchain-jd-com/jdchain#48]
请问如果我在机器A中的配置文件动态增加了一个新的节点，那么在同一个链上的机器B能感知到这个新增加的节点吗，可以的话能告知下源码在哪里吗

**Comment by zhaoGuangwei** [comment]
配置文件只是用来在初始化阶段把配置信息存入DB中，然后链从DB中读取配置信息使用。所以配置文件动态新增节点目前达不到效果，可以通过sdk的方式新增节点，不过目前还是半自动的方式，如果感兴趣，可以看看：https://3.cn/CagJrfM。

**Comment by qq511340079** [comment]
明白了谢谢
