### ISSUE TITLE
1.0.0升级1.1.2,用的rocksdb，原有的数据怎么保留

### ISSUE THREAD

**Issue by butterfly-sn** [blockchain-jd-com/jdchain#49]
这边在测试升级的时候，在ledger-binding.conf中的数据库地址指向原本的rocksdb文件夹，节点报错com.jd.blockchain.peer.web.ManagementController 217 setConfig - Error occurred on configing LedgerBindingConfig! --Ledger doesn't exist! java.lang.RuntimeException: Ledger doesn't exist!

**Comment by zhaoGuangwei** [comment]
目前由于两个版本的内部结构有所不同，不能直接替换。替代方案是：通过对应的API接口（3.3根据高度获得区块详细信息），从原先的老系统中获取相应数据，然后进行迁移。

**Comment by huanghaiquan** [comment]
我们正在考虑在后续版本提供解决方案。

**Comment by butterfly-sn** [comment]
好的
