### ISSUE TITLE
Failed to execute mvn clean package - missing the com.yahoo.ycsb:core:jar:0.1.4

### ISSUE THREAD

**Issue by junahan** [blockchain-jd-com/jdchain#5]
[INFO] consensus-bftsmart ................................. FAILURE [  0.031 s]
[INFO] consensus-mq ....................................... SKIPPED
[INFO] storage-redis ...................................... SKIPPED
[INFO] storage-rocksdb .................................... SKIPPED
[INFO] storage-composite .................................. SKIPPED
[INFO] gateway ............................................ SKIPPED
[INFO] tools-initializer .................................. SKIPPED
[INFO] peer ............................................... SKIPPED
[INFO] sdk-samples ........................................ SKIPPED
[INFO] tools-keygen-booter ................................ SKIPPED
[INFO] tools-initializer-booter ........................... SKIPPED
[INFO] tools-capability ................................... SKIPPED
[INFO] test ............................................... SKIPPED
[INFO] test-consensus-client .............................. SKIPPED
[INFO] test-consensus-node ................................ SKIPPED
[INFO] test-ledger-core ................................... SKIPPED
[INFO] test-integration ................................... SKIPPED
[INFO] deployment ......................................... SKIPPED
[INFO] deployment-gateway ................................. SKIPPED
[INFO] deployment-peer .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.338 s
[INFO] Finished at: 2019-04-16T12:30:29+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project consensus-bftsmart: Could not resolve dependencies for project com.jd.blockchain:consensus-bftsmart:jar:0.8.3.RELEASE: Failure to find com.yahoo.ycsb:core:jar:0.1.4 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :consensus-bftsmart

**Comment by zhaoGuangwei** [comment]
ok,可能是版本不一致导致。

**Comment by junahan** [comment]
没明白，显然是依赖的 com.yahoo.ycsb:core:jar 包并不在默认的 center repository 上，而是在http://kompics.sics.se/maven/repository/ 上，需要在 POM 里面配置该 repository  才行。
