### ISSUE TITLE
数据检索系统（Argus）使用问题-grpc error

### ISSUE THREAD

**Issue by zhaoGuangwei** [blockchain-jd-com/jdchain#50]
记录一下用户反馈的问题：
       我是一位区块链技术爱好者，目前在用到Argus的过程中遇到了一个问题，一直没找到对应的资料，也没有找到对应的开源源代码，希望能够帮看下是什么原因造成的。
![image](https://user-images.githubusercontent.com/6849792/76816493-5bc1ad00-683b-11ea-8f80-83579c5fa443.png)

网关日志输出：
request = {http://192.168.1.90:10001/ledgers/j5uvbVV7S6vS7FzyWG4RujUeLEv2gBEMTY7pkzY4gCho8R/all/search?keyword=LdeNoBXaBSA4BYfL9oBa1Yx79BNTadTgvGjLi} 
 result = {{"success":false,"error":{"errorCode":1,"errorMessage":"rpc error: code = Internal desc = grpc: error unmarshalling request: proto: wrong wireType = 2 for field StartTs"}}} 

查看api-server.log日志文件输出：
---> {
		query_ledgers(func: has(ledger-hash_id)) @normalize
		{
			uid
		     status-ledger:ledger-hash_id
             status-height:count(ledger-block)
        }
    }  (searcher/query)[2020-03-14 14:53:32]
**** query ledger from dgraph failed: rpc error: code = Internal desc = grpc: error unmarshalling request: proto: wrong wireType = 2 for field StartTs  (searcher/query)[2020-03-14 14:53:32]
**** While try to query failed: rpc error: code = Internal desc = grpc: error unmarshalling request: proto: wrong wireType = 2 for field StartTs  (searcher/query)[2020-03-14 14:53:46]

查看ledger-rdf.log日志文件输出：
**** While try to query failed: rpc error: code = Internal desc = grpc: error unmarshalling request: proto: wrong wireType = 2 for field StartTs  (helper)[2020-03-14 14:54:36]
**** --------------------------------------------------------------------------------------------------------------------------------  (helper)[2020-03-14 14:54:36]
---> {
        query_node(func: eq(ledger-hash_id, "j5uvbVV7S6vS7FzyWG4RujUeLEv2gBEMTY7pkzY4gCho8R")) {
            uid
            expand(_all_)
        }
    }  (helper)[2020-03-14 14:54:36]

经过反复查看、验证http://ledger.jd.com/argus.html中提供的方法，仍然解决不了这个问题，希望贵公司该项目的技术人员能够帮排查下是什么原因造成的，该怎么解决，谢谢！

**Comment by klboke** [comment]
这个就是dgraph的版本问题导致的，默认指令安装的最新的版本是有兼容问题的

**Comment by zhaoGuangwei** [comment]
凯玲回复的很及时啊，多谢！我给你再记上一笔，感谢您对JDChain的持续关注！
目前最新版本确实有这个问题。目前支持的是dgraph v1.0.16版本，新版本目前未兼容。

可以参考这几篇文章看看：
https://zhuanlan.zhihu.com/p/101664039
https://zhuanlan.zhihu.com/p/101666639
如果有问题，大家再及时跟我们沟通。
