### ISSUE TITLE
拆分合约创建和合约提交接口，异步化更适合用户和认证系统进行签名

### ISSUE THREAD

**Issue by chenylh** [blockchain-jd-com/jdchain#52]
![image](https://user-images.githubusercontent.com/20794673/77025104-43809800-69cb-11ea-90fe-0c066e4a0840.png)

**Comment by huanghaiquan** [comment]
您是否是在使用中遇到了难以实现的需求？可以通过邮箱  jdchain-support@jd.com 和我们取得联系，提出并讨论您想法。

感谢您的关注。
