### ISSUE TITLE
在合约内部想获取签名的信息，返回异常

### ISSUE THREAD

**Issue by zhaoGuangwei** [blockchain-jd-com/jdchain#57]
我在本地创建了一个合约，在合约内部想获取签名的信息，参照了AssetContractImpl类的实现方法，然而合约调用时，我尝试了几次，都得到SYSTEM_ERROR 的失败信息。不知道是什么问题
![image](https://user-images.githubusercontent.com/6849792/78089092-dcb2a400-73f8-11ea-9a01-b31602074d6c.png)

合约内部其他的方法调用，经过测试是没有问题的，只有这种涉及到签名的，都会报错

**Comment by zhaoGuangwei** [comment]
经验证，基于1.1.4.RELEASE版本获取签名信息时，会报异常，我们会紧急修复这个问题。

**Comment by evsward** [comment]
☺

**Comment by zhaoGuangwei** [comment]
此问题已经在1.3.0版本修复，感谢反馈者。
