### ISSUE TITLE
是否有方法查询该用户绑定的角色

### ISSUE THREAD

**Issue by zhaoGuangwei** [blockchain-jd-com/jdchain#63]
你好，请问一下jd-chain中如何知道某个用户的角色呢？我看jdchain-starter-master示例代码contract-starter目录下的test文件中SDKDemo_RegisterUser类中有一个registerRole方法，用户注册的时候可以给他赋予角色相关的权限。请问是否有方法查询该用户绑定的角色呢
![image](https://user-images.githubusercontent.com/6849792/80356079-83307e80-88ab-11ea-9323-99b3d937a5b4.png)

**Comment by zhaoGuangwei** [comment]
目前这个接口还没有对外提供，感谢这位用户的关注。此功能后续会优先排期。

**Comment by yuqian0218** [comment]
@zhaoGuangwei 请问截图是我们JD Chain 的开发者群么？能否提供一下群信息，求加入

**Comment by zhaoGuangwei** [comment]
> @zhaoGuangwei 请问截图是我们JD Chain 的开发者群么？能否提供一下群信息，求加入
抱歉，近期才统一处理这个issue。你可以加我微信号:vitty_zhao，我把你拉入群吧。

**Comment by zhaoGuangwei** [comment]
1.3.0版本已经提供了基于角色的查询接口，具体参考：http://ledger.jd.com/api.html 中第10节，感谢问题反馈者。
