### ISSUE TITLE
穿透式检索的argus是否是开源的，能否给一个开源地址？网上关于这个组件信息很少

### ISSUE THREAD

**Issue by liurf2** [blockchain-jd-com/jdchain#66]
穿透式检索的argus是否是开源的，能否给一个开源地址？网上关于这个组件信息很少
能否多公布一些这个组件的信息，否则感觉是个黑盒子

**Comment by zhaoGuangwei** [comment]
目前穿透式检索是一个实验性产品，还未开源，抱歉。
