### ISSUE TITLE
API问题：获取某特定区块的交易列表会报错

### ISSUE THREAD

**Issue by evsward** [blockchain-jd-com/jdchain#67]
目前使用的是jdchian 1.3.0版本，通过浏览器访问交易列表api，遇到一个奇怪的问题：

api示例，成功：/ledgers/j5wicGMLtw8NPQjRy1dwycZVQwNQUR5CLK27baTpyACSvF/blocks/height/196/txs

api示例，失败：/ledgers/j5wicGMLtw8NPQjRy1dwycZVQwNQUR5CLK27baTpyACSvF/blocks/height/193/txs

**Comment by zhaoGuangwei** [comment]
抱歉，此时才回复此问题。这个问题需要分析日志才能准确定位，如果下次遇到此类问题，请及时给我们发邮件：jdchain-support@jd.com。感谢！
