### ISSUE TITLE
http://192.168.1.151:8000/#/ledgers 查看帐本时，状态一直为未加载.

### ISSUE THREAD

**Issue by galnt** [blockchain-jd-com/jdchain#68]

**Comment by galnt** [comment]
安装指导文档说启动完成状态会变更，多次安装，单台机器和多台机器安装均无法正常显示已加载。

-------- lib jars --------
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/utils-web-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/utils-serialize-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/utils-http-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/utils-common-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/tools-keygen-booter-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/tools-keygen-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/tools-initializer-booter-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/tools-initializer-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/tomcat-embed-websocket-9.0.31.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/tomcat-embed-el-9.0.31.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/tomcat-embed-core-9.0.31.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/storage-service-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/spring-webmvc-5.2.4.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/spring-web-5.2.4.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/spring-security-web-5.2.2.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/spring-security-core-5.2.2.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/spring-security-config-5.2.2.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/spring-jcl-5.2.4.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/spring-expression-5.2.4.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/spring-core-5.2.4.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/spring-context-5.2.4.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/spring-boot-starter-web-2.2.5.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/spring-boot-starter-validation-2.2.5.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/spring-boot-starter-tomcat-2.2.5.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/spring-boot-starter-security-2.2.5.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/spring-boot-starter-log4j2-2.2.5.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/spring-boot-starter-json-2.2.5.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/spring-boot-starter-2.2.5.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/spring-boot-autoconfigure-2.2.5.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/spring-boot-2.2.5.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/spring-beans-5.2.4.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/spring-aop-5.2.4.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/snakeyaml-1.25.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/slf4j-api-1.7.25.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/sdk-rpc-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/sdk-base-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/runtime-context-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/rocksdbjni-6.3.6.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/reflections-0.9.10.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/procyon-reflection-0.5.35.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/procyon-expressions-0.5.35.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/procyon-core-0.5.35.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/procyon-compilertools-0.5.35.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/netty-all-4.1.45.Final.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/manager-explorer-1.2.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/log4j-slf4j-impl-2.12.1.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/log4j-jul-2.12.1.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/log4j-core-2.10.0.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/log4j-api-2.10.0.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/ledger-model-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/ledger-database-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/kvdb-protocol-1.0.1.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/kvdb-client-1.0.1.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/jul-to-slf4j-1.7.25.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/jnats-2.2.0.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/jedis-2.9.0.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/jboss-logging-3.4.1.Final.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/javassist-3.19.0-GA.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/jakarta.validation-api-2.0.2.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/jakarta.annotation-api-1.3.5.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/jackson-module-parameter-names-2.10.2.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/jackson-datatype-jsr310-2.10.2.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/jackson-datatype-jdk8-2.10.2.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/jackson-databind-2.10.2.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/jackson-core-2.10.2.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/jackson-annotations-2.10.2.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/httpcore-4.4.13.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/httpclient-4.5.1.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/hibernate-validator-6.0.18.Final.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/guava-19.0.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/fastjson-1.2.67.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/eddsa-0.1.0.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/disruptor-3.4.2.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/deploy-peer-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/crypto-sm-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/crypto-framework-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/crypto-classic-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/contract-jvm-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/contract-framework-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/consensus-mq-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/consensus-framework-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/consensus-bftsmart-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/commons-pool2-2.7.0.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/commons-logging-1.2.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/commons-io-2.4.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/commons-collections4-4.1.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/commons-codec-1.13.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/classmate-1.5.1.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/binary-proto-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/bft-smart-0.6.3.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/bcprov-jdk15on-1.61.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/bcpkix-jdk15on-1.61.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/base-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/annotations-2.0.1.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/libs/amqp-client-5.7.3.jar
-----------------
-------- system jars --------
0: file:/opt/jdchain-peer-1.3.0.RELEASE/system/storage-rocksdb-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/system/storage-redis-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/system/storage-kvdb-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/system/storage-composite-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/system/runtime-modular-booter-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/system/runtime-modular-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/system/peer-1.3.0.RELEASE.jar
0: file:/opt/jdchain-peer-1.3.0.RELEASE/system/deploy-peer-1.3.0.RELEASE.jar
-----------------
Load configuration,ledgerBindConfigFile position=/opt/jdchain-peer-1.3.0.RELEASE/config/ledger-binding.conf

 ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄        ▄▄▄▄▄▄▄▄▄▄   ▄            ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄    ▄       ▄▄▄▄▄▄▄▄▄▄▄  ▄         ▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄        ▄
▐░░░░░░░░░░░▌▐░░░░░░░░░░▌      ▐░░░░░░░░░░▌ ▐░▌          ▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░▌  ▐░▌     ▐░░░░░░░░░░░▌▐░▌       ▐░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░▌      ▐░▌
 ▀▀▀▀▀█░█▀▀▀ ▐░█▀▀▀▀▀▀▀█░▌     ▐░█▀▀▀▀▀▀▀█░▌▐░▌          ▐░█▀▀▀▀▀▀▀█░▌▐░█▀▀▀▀▀▀▀▀▀ ▐░▌ ▐░▌      ▐░█▀▀▀▀▀▀▀▀▀ ▐░▌       ▐░▌▐░█▀▀▀▀▀▀▀█░▌ ▀▀▀▀█░█▀▀▀▀ ▐░▌░▌     ▐░▌
      ▐░▌    ▐░▌       ▐░▌     ▐░▌       ▐░▌▐░▌          ▐░▌       ▐░▌▐░▌          ▐░▌▐░▌       ▐░▌          ▐░▌       ▐░▌▐░▌       ▐░▌     ▐░▌     ▐░▌▐░▌    ▐░▌
      ▐░▌    ▐░▌       ▐░▌     ▐░█▄▄▄▄▄▄▄█░▌▐░▌          ▐░▌       ▐░▌▐░▌          ▐░▌░▌        ▐░▌          ▐░█▄▄▄▄▄▄▄█░▌▐░█▄▄▄▄▄▄▄█░▌     ▐░▌     ▐░▌ ▐░▌   ▐░▌
      ▐░▌    ▐░▌       ▐░▌     ▐░░░░░░░░░░▌ ▐░▌          ▐░▌       ▐░▌▐░▌          ▐░░▌         ▐░▌          ▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌     ▐░▌     ▐░▌  ▐░▌  ▐░▌
      ▐░▌    ▐░▌       ▐░▌     ▐░█▀▀▀▀▀▀▀█░▌▐░▌          ▐░▌       ▐░▌▐░▌          ▐░▌░▌        ▐░▌          ▐░█▀▀▀▀▀▀▀█░▌▐░█▀▀▀▀▀▀▀█░▌     ▐░▌     ▐░▌   ▐░▌ ▐░▌
      ▐░▌    ▐░▌       ▐░▌     ▐░▌       ▐░▌▐░▌          ▐░▌       ▐░▌▐░▌          ▐░▌▐░▌       ▐░▌          ▐░▌       ▐░▌▐░▌       ▐░▌     ▐░▌     ▐░▌    ▐░▌▐░▌
 ▄▄▄▄▄█░▌    ▐░█▄▄▄▄▄▄▄█░▌     ▐░█▄▄▄▄▄▄▄█░▌▐░█▄▄▄▄▄▄▄▄▄ ▐░█▄▄▄▄▄▄▄█░▌▐░█▄▄▄▄▄▄▄▄▄ ▐░▌ ▐░▌      ▐░█▄▄▄▄▄▄▄▄▄ ▐░▌       ▐░▌▐░▌       ▐░▌ ▄▄▄▄█░█▄▄▄▄ ▐░▌     ▐░▐░▌
▐░░░░░░░▌    ▐░░░░░░░░░░▌      ▐░░░░░░░░░░▌ ▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░▌  ▐░▌     ▐░░░░░░░░░░░▌▐░▌       ▐░▌▐░▌       ▐░▌▐░░░░░░░░░░░▌▐░▌      ▐░░▌
 ▀▀▀▀▀▀▀      ▀▀▀▀▀▀▀▀▀▀        ▀▀▀▀▀▀▀▀▀▀   ▀▀▀▀▀▀▀▀▀▀▀  ▀▀▀▀▀▀▀▀▀▀▀  ▀▀▀▀▀▀▀▀▀▀▀  ▀    ▀       ▀▀▀▀▀▀▀▀▀▀▀  ▀         ▀  ▀         ▀  ▀▀▀▀▀▀▀▀▀▀▀  ▀        ▀▀


09:56:41.283 INFO  org.springframework.boot.StartupInfoLogger 55 logStarting - Starting application on localhost.localdomain with PID 6558 (started by root in /opt/jdchain-peer-1.3.0.RELEASE/bin)
09:56:41.533 INFO  org.springframework.boot.SpringApplication 651 logStartupProfileInfo - No active profile set, falling back to default profiles: default
09:56:43.197 INFO  org.springframework.boot.web.embedded.tomcat.TomcatWebServer 92 initialize - Tomcat initialized with port(s): 7080 (http)
09:56:43.222 INFO  org.apache.juli.logging.DirectJDKLog 173 log - Initializing ProtocolHandler ["http-nio-0.0.0.0-7080"]
09:56:43.223 INFO  org.apache.juli.logging.DirectJDKLog 173 log - Starting service [Tomcat]
09:56:43.224 INFO  org.apache.juli.logging.DirectJDKLog 173 log - Starting Servlet engine: [Apache Tomcat/9.0.31]
09:56:43.303 INFO  org.apache.juli.logging.DirectJDKLog 173 log - Initializing Spring embedded WebApplicationContext
09:56:43.303 INFO  org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext 284 prepareWebApplicationContext - Root WebApplicationContext: initialization completed in 1721 ms
09:56:43.557 INFO  org.reflections.Reflections 229 scan - Reflections took 55 ms to scan 5 urls, producing 16 keys and 49 values
09:56:43.863 INFO  org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration 86 getOrDeducePassword -

Using generated security password: f231a578-b4b4-4c24-ba01-a08f6667ad38

09:56:43.984 INFO  org.springframework.security.web.DefaultSecurityFilterChain 43 <init> - Creating filter chain: any request, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@22ebccb9, org.springframework.security.web.context.SecurityContextPersistenceFilter@529c2a9a, org.springframework.security.web.header.HeaderWriterFilter@ed91d8d, org.springframework.security.web.authentication.logout.LogoutFilter@527fc8e, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@26bbe604, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@80bfa9d, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@5875de6a, org.springframework.security.web.session.SessionManagementFilter@1cf0cacc, org.springframework.security.web.access.ExceptionTranslationFilter@59bbe88a, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@2d4608a6]
09:56:44.149 INFO  org.springframework.scheduling.concurrent.ExecutorConfigurationSupport 181 initialize - Initializing ExecutorService 'applicationTaskExecutor'
09:56:44.279 INFO  org.springframework.boot.autoconfigure.web.servlet.WelcomePageHandlerMapping 54 <init> - Adding welcome page: class path resource [META-INF/resources/index.html]
09:56:44.351 INFO  org.springframework.scheduling.concurrent.ExecutorConfigurationSupport 181 initialize - Initializing ExecutorService 'taskScheduler'
09:56:44.381 INFO  org.apache.juli.logging.DirectJDKLog 173 log - Starting ProtocolHandler ["http-nio-0.0.0.0-7080"]
09:56:44.424 INFO  org.springframework.boot.web.embedded.tomcat.TomcatWebServer 204 start - Tomcat started on port(s): 7080 (http) with context path ''
09:56:44.428 INFO  org.springframework.boot.StartupInfoLogger 61 logStarted - Started application in 3.635 seconds (JVM running for 4.617)
09:56:44.537 WARN  com.jd.blockchain.provider.ProviderManager$NamedProviders 156 install - The provider[com.jd.blockchain.crypto.service.classic.ClassicCryptoService] already exists.
09:56:44.538 WARN  com.jd.blockchain.provider.ProviderManager$NamedProviders 156 install - The provider[com.jd.blockchain.crypto.service.sm.SMCryptoService] already exists.
------ [[ max-parallel-dbwrite-size=500 ]] ------
09:56:44.874 INFO  com.jd.blockchain.consensus.bftsmart.service.BftsmartNodeServer 631 start - =============================== Start replica ===================================
09:56:44.874 INFO  com.jd.blockchain.consensus.bftsmart.service.BftsmartNodeServer 643 start - Start replica...[ID=0]
09:56:44.924 ERROR bftsmart.communication.server.ServerConnection$ReceiverThread 621 run - [ServerConnection.ReceiverThread] I will waitAndConnect connect with 3
09:56:44.926 ERROR bftsmart.communication.server.ServerConnection$ReceiverThread 621 run - [ServerConnection.ReceiverThread] I will waitAndConnect connect with 1
09:56:44.926 ERROR bftsmart.communication.server.ServerConnection$ReceiverThread 621 run - [ServerConnection.ReceiverThread] I will waitAndConnect connect with 2
09:56:45.117 INFO  bftsmart.communication.client.netty.NettyClientServerCommunicationSystemServerSide 104 <init> - -- ID = 0
09:56:45.117 INFO  bftsmart.communication.client.netty.NettyClientServerCommunicationSystemServerSide 105 <init> - -- N = 4
09:56:45.118 INFO  bftsmart.communication.client.netty.NettyClientServerCommunicationSystemServerSide 106 <init> - -- F = 1
09:56:45.118 INFO  bftsmart.communication.client.netty.NettyClientServerCommunicationSystemServerSide 107 <init> - -- Port = 6300
09:56:45.118 INFO  bftsmart.communication.client.netty.NettyClientServerCommunicationSystemServerSide 108 <init> - -- requestTimeout = 60000
09:56:45.118 INFO  bftsmart.communication.client.netty.NettyClientServerCommunicationSystemServerSide 109 <init> - -- maxBatch = 2000
09:56:45.119 INFO  bftsmart.communication.client.netty.NettyClientServerCommunicationSystemServerSide 110 <init> - -- Using MACs
09:56:45.119 INFO  bftsmart.tom.ServiceReplica 344 init - -- In current view: ID:0; F:1; Processes:0(/192.168.1.151:6300),1(/192.168.1.152:6300),2(/192.168.1.153:6300),3(/192.168.1.154:6300),
09:56:47.482 INFO  bftsmart.communication.server.ServerConnection 463 authenticateAndEstablishAuthKey - I am proc 0, -- Diffie-Hellman complete with proc id 1, with port 6301
09:56:49.094 INFO  bftsmart.communication.server.ServerConnection 463 authenticateAndEstablishAuthKey - I am proc 0, -- Diffie-Hellman complete with proc id 2, with port 6301
09:56:49.926 ERROR bftsmart.communication.server.ServerConnection$ReceiverThread 621 run - [ServerConnection.ReceiverThread] I will waitAndConnect connect with 3
09:56:49.934 INFO  bftsmart.statemanagement.strategy.BaseStateManager 254 currentConsensusIdReceived - -- Replica state is up to date
09:56:50.002 WARN  com.jd.blockchain.peer.web.LedgerLoadTimer 109 ledgerLoad - --- Can not get semaphore of load ledger !!!
09:56:50.154 INFO  com.jd.blockchain.consensus.bftsmart.service.BftsmartNodeServer 650 start - =============================== Replica started success! ===================================
09:56:50.890 INFO  bftsmart.communication.server.ServerConnection 463 authenticateAndEstablishAuthKey - I am proc 0, -- Diffie-Hellman complete with proc id 3, with port 6301
10:15:45.819 INFO  org.apache.juli.logging.DirectJDKLog 173 log - Initializing Spring DispatcherServlet 'dispatcherServlet'
10:15:45.820 INFO  org.springframework.web.servlet.FrameworkServlet 525 initServletBean - Initializing Servlet 'dispatcherServlet'
10:15:45.828 INFO  org.springframework.web.servlet.FrameworkServlet 547 initServletBean - Completed initialization in 7 ms
10:15:46.025 INFO  com.jd.blockchain.consensus.bftsmart.service.BftsmartNodeServer 252 getOuterTopology - [BftsmartNodeServer.getOuterTopology] PartiNode id = 0, host = 192.168.1.151, port = 6300
10:15:46.037 INFO  com.jd.blockchain.consensus.bftsmart.service.BftsmartNodeServer 252 getOuterTopology - [BftsmartNodeServer.getOuterTopology] PartiNode id = 1, host = 192.168.1.152, port = 6300
10:15:46.051 INFO  com.jd.blockchain.consensus.bftsmart.service.BftsmartNodeServer 252 getOuterTopology - [BftsmartNodeServer.getOuterTopology] PartiNode id = 2, host = 192.168.1.153, port = 6300
10:15:46.065 INFO  com.jd.blockchain.consensus.bftsmart.service.BftsmartNodeServer 252 getOuterTopology - [BftsmartNodeServer.getOuterTopology] PartiNode id = 3, host = 192.168.1.154, port = 6300

这个是节点

**Comment by shaozhuguang** [comment]
@galnt  网关节点有报什么错误吗？

**Comment by huanghaiquan** [comment]
由于提供的信息有限，难以进一步帮助您进行定位，故此先关闭此问题，如果补充信息欢迎再次反馈。

另外，目前 1.4.0.RELEASE 版本已经发布，新增了共识节点的动态添加移除功能，并且在共识算法的稳定性上有重大提升，欢迎关注。
