### ISSUE TITLE
项目启动后，peer节点的/tmp/下 tomcat的access_log一天能占用十几个g

### ISSUE THREAD

**Issue by ilaotan** [blockchain-jd-com/jdchain#69]
项目启动后，peer节点的/tmp/下 tomcat的access_log一天能占用十几个g 请问如何解决？虽然用了springboot，我看了代码，反射+少数几个可配置参数，没找到可传入参数 能让我把这个日志可配置。

**Comment by ilaotan** [comment]
仓库里版本好乱，我想自己改改，打个包都打不起来，1.2.1  1.3.0  1.4快照 我真呵呵哒了

**Comment by shaozhuguang** [comment]
@ilaotan  试一下
--spring.config.addition-location=/usr/local/java/application.properties  这个参数呢？后面的application.properties改为自己的路径

**Comment by huanghaiquan** [comment]
最新的 1.4.0.RELEASE 版本优化了日志的默认配置以减少日常运行中不必要的日志输出，欢迎关注。
