### ISSUE TITLE
failed to build - dependency package browser:0.6.6 is not exist in center repository.

### ISSUE THREAD

**Issue by junahan** [blockchain-jd-com/jdchain#7]
[INFO] gateway 0.9.0-SNAPSHOT ............................. FAILURE [  0.149 s]
[INFO] tools-initializer 0.9.0-SNAPSHOT ................... SKIPPED
[INFO] peer 0.9.0-SNAPSHOT ................................ SKIPPED
[INFO] sdk-samples 0.9.0-SNAPSHOT ......................... SKIPPED
[INFO] tools-keygen-booter 0.9.0-SNAPSHOT ................. SKIPPED
[INFO] tools-initializer-booter 0.9.0-SNAPSHOT ............ SKIPPED
[INFO] tools-capability 0.9.0-SNAPSHOT .................... SKIPPED
[INFO] test 0.9.0-SNAPSHOT ................................ SKIPPED
[INFO] test-consensus-client 0.9.0-SNAPSHOT ............... SKIPPED
[INFO] test-consensus-node 0.9.0-SNAPSHOT ................. SKIPPED
[INFO] test-ledger-core 0.9.0-SNAPSHOT .................... SKIPPED
[INFO] test-integration 0.9.0-SNAPSHOT .................... SKIPPED
[INFO] deployment 0.9.0-SNAPSHOT .......................... SKIPPED
[INFO] deployment-gateway 0.9.0-SNAPSHOT .................. SKIPPED
[INFO] deployment-peer 0.9.0-SNAPSHOT ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.736 s
[INFO] Finished at: 2019-04-17T14:22:21+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project gateway: Could not resolve dependencies for project com.jd.blockchain:gateway:jar:0.9.0-SNAPSHOT: Failure to find com.jd.blockchain:browser:jar:0.6.6.RELEASE in http://central.maven.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]

**Comment by zhaoGuangwei** [comment]
OK，版本要保持一致。

**Comment by junahan** [comment]
可以确认 com.jd.blockchain:browser:jar:0.6.6.RELEASE 还没有被 push 到 center repository，所以导致该依赖包找不到。

**Comment by springtty** [comment]
> 可以确认 com.jd.blockchain:browser:jar:0.6.6.RELEASE 还没有被 push 到 center repository，所以导致该依赖包找不到。

上面只有一个0.6.5版本的包，不知道能不能适用。
