### ISSUE TITLE
NoClassDefFoundError: sun/jvmstat/monitor/MonitoredHost

### ISSUE THREAD

**Issue by fangweilong** [blockchain-jd-com/jdchain#76]
版本：1.4.2
jdk：openjdkl 1.8
服务器：centos7.6

报错：org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: sun/jvmstat/monitor/MonitoredHost

出现这个问题是因为toools.jar找不到，需要将jdk下 lib/tools.jar 复制到每一个peer的libs目录下，并重新启动项目。
建议更新文档标明此处使用提示

**Comment by imuge** [comment]
感谢 @fangweilong ，已添加[FAQ](https://github.com/blockchain-jd-com/jdchain/wiki/FAQ)页并将持续补充常见问题
