### ISSUE TITLE
初始化账本报错，我创建了4个用户，配置文件也按照文档设置好了，这个报错大概出错在什么位置？

### ISSUE THREAD

**Issue by lambossnow** [blockchain-jd-com/jdchain#8]
[InitServiceExceptionHandler] Error of web controllers! --The requester signature is invalid!

**Comment by springtty** [comment]
mark，遇到同样的问题。

**Comment by huanghaiquan** [comment]
The ledger.seed of the four nodes is to use the same random number.

**Comment by springtty** [comment]
> The ledger.seed of the four nodes is to use the same random number.

我尝试四个节点ledger.seed取同样的值，就是配置文件ledger-init.conf中默认的值，最后会报错：
Error!! -- Participant already exist! --[id=QV91s7Ngqri1u5ujD2hdd2fFGHeEwiCGR9AnoGqed8ETsN6UB]

**Comment by springtty** [comment]
> 4 nodes require 4 different public keys.

4个节点都使用keygen.sh重新生成了密钥对的，配置文件都进行了修改。按您上面的意思是不是说ledger.seed应该相同？如果是这样的话，开始就报错 Participant already exist！有点想不通了。

**Comment by karott** [comment]
ledger.seed我四个节点都是一样的，没问题；每个peer节点的密钥不能一样吧

**Comment by lambossnow** [comment]
是的，我修改了各自的ledger.seed，因为我认为是初始化四个账本，这一点应该加入到文档说明中

**Comment by lambossnow** [comment]
ok
