### ISSUE TITLE
运行初始化脚本出错，java运行报错

### ISSUE THREAD

**Issue by peter5232** [blockchain-jd-com/jdchain#89]
![图片](https://user-images.githubusercontent.com/58766816/149545669-1ab5b898-c5e0-4472-9fe3-5ecb99d8048b.png)
![图片](https://user-images.githubusercontent.com/58766816/149545712-f09160ba-d2be-4493-81a3-d27ceed87bc4.png)

Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @3bf44630

**Comment by klboke** [comment]
用jdk8 试试

**Comment by imuge** [comment]
1.6.3已实现8以上版本支持
