### ISSUE TITLE
如何进行节点扩展？

### ISSUE THREAD

**Issue by hoocen** [blockchain-jd-com/jdchain#91]
已经运行的链，怎么添加新的节点？如果有新的上下游企业加入链中，如何扩展企业自己的网关或节点？
![123](https://user-images.githubusercontent.com/10540077/153141408-f8b3ed72-d757-4c69-9f9a-bdd42f945a3d.png)

**Comment by imuge** [comment]
https://blockchain-jd-com.github.io/#/cli/participant @hoocen
